name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install npm
        run: npm i npm -g
      - name: Audit
        run: npm audit
