name: Test
on: [push, pull_request]

jobs:
  lint:
    name: Unit test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install npm
        run: npm i npm -g
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
